export const GENERAL_SUBJECTS = [
  {
    id: "tin-hoc",
    name: "Tin Học Đầu Ra",
    description: "Tin A, Tin B, Access",
    icon: "💻",
    color: "text-blue-600 dark:text-blue-400",
  },
  {
    id: "ngoai-ngu-dau-ra",
    name: "Ngoại Ngữ Đầu Ra",
    description: "AV1, AV2",
    icon: "🗣️",
    color: "text-red-600 dark:text-red-400",
  },
  {
    id: "dai-cuong",
    name: "Môn Đại Cương",
    description: "Pháp Luật ĐC, Tin Học ĐC",
    icon: "🌟",
    color: "text-amber-500 dark:text-amber-400",
  },
];

export const FACULTIES = [
  {
    id: "nong-hoc",
    name: "Khoa Nông Học",
    description: "",
    icon: "🌱",
    color: "text-green-600 dark:text-green-400",
  },
  {
    id: "lam-nghiep",
    name: "Khoa Lâm Nghiệp",
    description: "",
    icon: "🌲",
    color: "text-emerald-600 dark:text-emerald-400",
  },
  {
    id: "chan-nuoi-thu-y",
    name: "Khoa Chăn Nuôi Thú Y",
    description: "",
    icon: "🐕",
    color: "text-orange-600 dark:text-orange-400",
  },
  {
    id: "thuy-san",
    name: "Khoa Thủy Sản",
    description: "",
    icon: "🐟",
    color: "text-cyan-600 dark:text-cyan-400",
  },
  {
    id: "kinh-te",
    name: "Khoa Kinh Tế",
    description: "",
    icon: "📈",
    color: "text-amber-600 dark:text-amber-400",
  },
  {
    id: "co-khi-cong-nghe",
    name: "Khoa Cơ Khí Công Nghệ",
    description: "",
    icon: "⚙️",
    color: "text-slate-700 dark:text-slate-300",
  },
  {
    id: "hoa-thuc-pham",
    name: "Khoa Công Nghệ Hóa Học & Thực Phẩm",
    description: "",
    icon: "🧪",
    color: "text-pink-600 dark:text-pink-400",
  },
  {
    id: "cntt",
    name: "Khoa Công Nghệ Thông Tin",
    description: "",
    icon: "⌨️",
    color: "text-blue-600 dark:text-blue-400",
  },
  {
    id: "quan-ly-dat-dai",
    name: "Khoa Quản Lý Đất Đai & Bất Động Sản",
    description: "",
    icon: "🗺️",
    color: "text-yellow-600 dark:text-yellow-400",
  },
  {
    id: "khoa-hoc",
    name: "Khoa Khoa Học",
    description: "",
    icon: "🔬",
    color: "text-indigo-600 dark:text-indigo-400",
  },
  {
    id: "moi-truong",
    name: "Khoa Môi Trường & Tài Nguyên",
    description: "",
    icon: "🌍",
    color: "text-teal-600 dark:text-teal-400",
  },
  {
    id: "ngoai-ngu",
    name: "Khoa Ngoại Ngữ",
    description: "",
    icon: "🇬🇧",
    color: "text-purple-600 dark:text-purple-400",
  },
  {
    id: "sinh-hoc",
    name: "Khoa Khoa Học Sinh Học",
    description: "",
    icon: "🧬",
    color: "text-rose-600 dark:text-rose-400",
  },
];
